frontend:
  - "app/**"
  - "components/**"
  - "lib/**"
  - "public/**"
  - "styles/**"
  - "types/**"
  - "utils/**"
  - "_mock/**"

devops:
  - ".github/**"
  - "pnpm-lock.yaml"
  - "!app/**"
